# Generated by Django 5.1.7 on 2025-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.TextField(),
        ),
    ]
